version: '3'
services:
  back:
    hostname: back
    image: johnsteck/back
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-1
      - STORAGE_SOILSENSEDB_NAME=soilsense-dev
    build:
      dockerfile: ./back/Dockerfile
    deploy:
      x-aws-autoscaling:
        cpu: 1
        max: 3
    ports:
      - 5000:5000
  front:
    hostname: front
    depends_on:
      - back
    image: johnsteck/front
    build:
      dockerfile: ./front/Dockerfile
    ports:
      - 80:80
